name: Zane
favicon: null
layout_spectrum: 0.14139
title: Zane
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: 491ef7a5-5ac4-4991-aa08-928fd9c2235f
    url: null
